-- Vercel color scheme matching Ghostty Vercel theme
-- Based on the exact color palette from Ghostty's Vercel theme

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "vercel"
vim.o.termguicolors = true

-- Palette colors from Ghostty Vercel theme
local colors = {
  bg = "#000000",
  fg = "#fafafa",

  -- ANSI colors
  black = "#000000",
  red = "#fc0036",
  green = "#29a948",
  yellow = "#ffae00",
  blue = "#006aff",
  magenta = "#f32882",
  cyan = "#00ac96",
  white = "#feffff",

  -- Bright ANSI colors
  bright_black = "#1a1a1a",
  bright_red = "#ff8080",
  bright_green = "#4be15d",
  bright_yellow = "#ffae00",
  bright_blue = "#49aeff",
  bright_magenta = "#f97ea8",
  bright_cyan = "#00e4c4",
  bright_white = "#fefefe",

  -- Special colors
  cursor = "#f32882",
  selection_bg = "#005be7",
  selection_fg = "#fafafa",

  -- Additional UI colors
  comment = "#a8a8a8",
  line_highlight = "#161616",
  visual = "#005be7",
  gutter_fg = "#a8a8a8",
  gutter_bg = "#000000",
  document_highlight = "#282840",

  -- Custom colors for syntax
  purple = "#bf7af0", -- for functions
}

-- Helper function to set highlights
local function hi(group, opts)
  local cmd = "highlight " .. group
  if opts.fg then
    cmd = cmd .. " guifg=" .. opts.fg
  end
  if opts.bg then
    cmd = cmd .. " guibg=" .. opts.bg
  end
  if opts.gui then
    cmd = cmd .. " gui=" .. opts.gui
  end
  if opts.sp then
    cmd = cmd .. " guisp=" .. opts.sp
  end
  vim.cmd(cmd)
end

-- Editor highlights
hi("Normal", { fg = colors.fg, bg = colors.bg })
hi("NormalFloat", { fg = colors.fg, bg = colors.bg })
hi("NormalNC", { fg = colors.fg, bg = colors.bg })
hi("Comment", { fg = colors.comment, gui = "italic" })
hi("Constant", { fg = colors.bright_blue })
hi("String", { fg = colors.green })
hi("Character", { fg = colors.green })
hi("Number", { fg = colors.yellow })
hi("Boolean", { fg = colors.bright_blue })
hi("Float", { fg = colors.yellow })
hi("Identifier", { fg = colors.fg })
hi("Function", { fg = colors.purple }) -- purple/violet for functions
hi("Statement", { fg = colors.magenta }) -- use magenta for keywords
hi("Conditional", { fg = colors.magenta })
hi("Repeat", { fg = colors.magenta })
hi("Label", { fg = colors.magenta })
hi("Operator", { fg = colors.fg }) -- operators should be foreground color
hi("Keyword", { fg = colors.magenta })
hi("Exception", { fg = colors.red })
hi("PreProc", { fg = colors.magenta })
hi("Include", { fg = colors.magenta })
hi("Define", { fg = colors.magenta })
hi("Macro", { fg = colors.cyan })
hi("PreCondit", { fg = colors.cyan })
hi("Type", { fg = colors.bright_blue }) -- use blue instead of cyan
hi("StorageClass", { fg = colors.blue })
hi("Structure", { fg = colors.bright_blue })
hi("Typedef", { fg = colors.bright_blue })
hi("Special", { fg = colors.purple }) -- purple
hi("SpecialChar", { fg = colors.purple })
hi("Tag", { fg = colors.magenta })
hi("Delimiter", { fg = colors.fg })
hi("SpecialComment", { fg = colors.comment, gui = "italic" })
hi("Debug", { fg = colors.red })
hi("Underlined", { fg = colors.bright_blue, gui = "underline" })
hi("Error", { fg = colors.red, bg = colors.bg })
hi("ErrorMsg", { fg = colors.red })
hi("Warning", { fg = colors.yellow })
hi("WarningMsg", { fg = colors.yellow })
hi("Info", { fg = colors.bright_blue })
hi("Hint", { fg = colors.bright_cyan })
hi("Todo", { fg = colors.yellow, bg = colors.bg, gui = "bold" })

-- UI elements
hi("Cursor", { fg = colors.fg, bg = colors.cursor })
hi("lCursor", { fg = colors.bg, bg = colors.cursor })
hi("CursorIM", { fg = colors.bg, bg = colors.cursor })
hi("CursorLine", { bg = colors.line_highlight })
hi("CursorColumn", { bg = colors.line_highlight })
hi("CursorLineNr", { fg = colors.bright_magenta, bg = colors.line_highlight })
hi("LineNr", { fg = colors.gutter_fg, bg = colors.gutter_bg })
hi("Visual", { bg = colors.visual, gui = "bold" })
hi("VisualNOS", { bg = colors.visual, gui = "bold" })
hi("Search", { fg = colors.bg, bg = colors.yellow })
hi("IncSearch", { fg = colors.bg, bg = colors.bright_yellow })
hi("CurSearch", { fg = colors.bg, bg = colors.bright_yellow })
hi("Substitute", { fg = colors.bright_magenta, bg = "#2a2a2a" })
hi("MatchParen", { fg = colors.bright_magenta, bg = "#2a2a2a", gui = "bold" })
hi("ModeMsg", { fg = colors.fg, gui = "bold" })
hi("MoreMsg", { fg = colors.bright_blue })
hi("Conceal", { fg = colors.comment })
hi("Pmenu", { fg = colors.fg, bg = "#1a1a1a" })
hi("PmenuSel", { fg = colors.bg, bg = colors.bright_blue, gui = "bold" })
hi("PmenuSbar", { bg = "#2a2a2a" })
hi("PmenuThumb", { bg = colors.comment })
hi("PmenuExtra", { fg = colors.comment })
hi("PmenuExtraSel", { fg = colors.comment, bg = colors.bright_blue, gui = "bold" })
hi("StatusLine", { fg = colors.fg, bg = "#1a1a1a" })
hi("StatusLineNC", { fg = colors.comment, bg = "#1a1a1a" })
hi("TabLine", { fg = colors.comment, bg = "#1a1a1a" })
hi("TabLineFill", { bg = "#1a1a1a" })
hi("TabLineSel", { fg = colors.fg, bg = colors.bg })
hi("VertSplit", { fg = "#2a2a2a" })
hi("WinSeparator", { fg = "#2a2a2a" })
hi("WinBar", { fg = colors.bright_magenta })
hi("WinBarNC", { fg = colors.comment })
hi("Folded", { fg = colors.comment, bg = "#1a1a1a" })
hi("FoldColumn", { fg = colors.comment, bg = colors.gutter_bg })
hi("SignColumn", { fg = colors.fg, bg = colors.gutter_bg })
hi("SignColumnSB", { fg = colors.fg, bg = colors.bg })
hi("Directory", { fg = colors.bright_blue })
hi("Title", { fg = colors.bright_magenta, gui = "bold" })
hi("ColorColumn", { bg = "#1a1a1a" })
hi("NonText", { fg = colors.comment })
hi("Whitespace", { fg = "#2a2a2a" })
hi("SpecialKey", { fg = colors.comment })
hi("EndOfBuffer", { fg = colors.bg })
hi("QuickFixLine", { bg = "#2a2a2a", gui = "bold" })
hi("WildMenu", { bg = colors.comment })
hi("TermCursor", { fg = colors.bg, bg = colors.cursor })
hi("TermCursorNC", { fg = colors.bg, bg = colors.comment })
hi("FloatBorder", { fg = "#2a2a2a", bg = colors.bg })
hi("FloatTitle", { fg = colors.bright_magenta, bg = colors.bg, gui = "bold" })
hi("FloatShadow", { fg = colors.comment })
hi("NormalSB", { fg = colors.fg, bg = colors.bg })

-- Spelling
hi("SpellBad", { sp = colors.red, gui = "undercurl" })
hi("SpellCap", { sp = colors.yellow, gui = "undercurl" })
hi("SpellLocal", { sp = colors.bright_blue, gui = "undercurl" })
hi("SpellRare", { sp = colors.green, gui = "undercurl" })

-- Diff
hi("DiffAdd", { fg = colors.bright_green, bg = "#0a2a14" })
hi("DiffChange", { fg = colors.bright_yellow, bg = "#2a2a0a" })
hi("DiffDelete", { fg = colors.red, bg = "#2a0a0a" })
hi("DiffText", { fg = colors.bright_blue, bg = "#0a1a2a" })

-- Git signs
hi("GitSignsAdd", { fg = colors.green })
hi("GitSignsChange", { fg = colors.yellow })
hi("GitSignsDelete", { fg = colors.red })

-- LSP
hi("DiagnosticError", { fg = colors.red })
hi("DiagnosticWarn", { fg = colors.yellow })
hi("DiagnosticInfo", { fg = colors.bright_blue })
hi("DiagnosticHint", { fg = colors.bright_cyan })
hi("DiagnosticUnderlineError", { sp = colors.red, gui = "undercurl" })
hi("DiagnosticUnderlineWarn", { sp = colors.yellow, gui = "undercurl" })
hi("DiagnosticUnderlineInfo", { sp = colors.bright_blue, gui = "undercurl" })
hi("DiagnosticUnderlineHint", { sp = colors.bright_cyan, gui = "undercurl" })

-- LSP Document Highlighting (subtle background for references)
hi("LspReferenceText", { bg = colors.document_highlight })
hi("LspReferenceRead", { bg = colors.document_highlight })
hi("LspReferenceWrite", { bg = colors.document_highlight })

-- Treesitter
hi("@variable", { fg = colors.fg })
hi("@variable.builtin", { fg = colors.blue })
hi("@variable.parameter", { fg = colors.fg })
hi("@variable.member", { fg = colors.fg })
hi("@constant", { fg = colors.bright_blue })
hi("@constant.builtin", { fg = colors.blue })
hi("@module", { fg = colors.fg })
hi("@string", { fg = colors.green })
hi("@string.escape", { fg = colors.purple }) -- purple
hi("@string.regexp", { fg = colors.cyan })
hi("@character", { fg = colors.green })
hi("@number", { fg = colors.yellow })
hi("@boolean", { fg = colors.blue })
hi("@function", { fg = colors.purple }) -- purple/violet for functions
hi("@function.builtin", { fg = colors.purple })
hi("@function.method", { fg = colors.fg }) -- methods should be foreground
hi("@constructor", { fg = colors.bright_blue })
hi("@keyword", { fg = colors.magenta }) -- use magenta
hi("@keyword.function", { fg = colors.magenta })
hi("@keyword.operator", { fg = colors.magenta })
hi("@keyword.return", { fg = colors.magenta })
hi("@operator", { fg = colors.fg }) -- operators should be foreground
hi("@punctuation.delimiter", { fg = colors.fg })
hi("@punctuation.bracket", { fg = colors.fg })
hi("@type", { fg = colors.bright_blue }) -- use blue
hi("@type.builtin", { fg = colors.bright_blue })
hi("@attribute", { fg = colors.cyan })
hi("@property", { fg = colors.fg })
hi("@tag", { fg = colors.magenta }) -- tags use magenta
hi("@tag.attribute", { fg = colors.fg })
hi("@tag.delimiter", { fg = colors.comment })

-- LSP Semantic Tokens (prevent LSP from overriding Treesitter)
hi("@lsp.type.namespace", { fg = colors.fg })
hi("@lsp.type.type", { fg = colors.bright_blue })
hi("@lsp.type.class", { fg = colors.bright_blue })
hi("@lsp.type.enum", { fg = colors.bright_blue })
hi("@lsp.type.interface", { fg = colors.bright_blue })
hi("@lsp.type.struct", { fg = colors.bright_blue })
hi("@lsp.type.parameter", { fg = colors.fg })
hi("@lsp.type.variable", { fg = colors.fg })
hi("@lsp.type.property", { fg = colors.fg })
hi("@lsp.type.enumMember", { fg = colors.bright_blue })
hi("@lsp.type.function", { fg = colors.purple })
hi("@lsp.type.method", { fg = colors.fg })
hi("@lsp.type.macro", { fg = colors.cyan })
hi("@lsp.type.decorator", { fg = colors.cyan })
hi("@lsp.type.keyword", { fg = colors.magenta })
hi("@lsp.type.comment", { fg = colors.comment })
hi("@lsp.type.string", { fg = colors.green })
hi("@lsp.type.number", { fg = colors.yellow })
hi("@lsp.type.operator", { fg = colors.fg })

-- Telescope
hi("TelescopeBorder", { fg = colors.bright_black })
hi("TelescopePromptBorder", { fg = colors.bright_black })
hi("TelescopeResultsBorder", { fg = colors.bright_black })
hi("TelescopePreviewBorder", { fg = colors.bright_black })
hi("TelescopeSelection", { bg = colors.visual })
hi("TelescopeSelectionCaret", { fg = colors.bright_magenta })
hi("TelescopeMatching", { fg = colors.bright_yellow, gui = "bold" })

-- Neo-tree / NvimTree
hi("NeoTreeNormal", { fg = colors.fg, bg = colors.bg })
hi("NeoTreeNormalNC", { fg = colors.fg, bg = colors.bg })
hi("NeoTreeDirectoryName", { fg = colors.bright_blue })
hi("NeoTreeDirectoryIcon", { fg = colors.bright_blue })
hi("NeoTreeExpander", { fg = colors.comment })
hi("NeoTreeIndentMarker", { fg = colors.comment })
hi("NeoTreeRootName", { fg = colors.bright_blue, gui = "bold" })
hi("NeoTreeSymbolicLinkTarget", { fg = colors.magenta })
hi("NeoTreeModified", { fg = colors.yellow })
hi("NeoTreeGitAdded", { fg = colors.green })
hi("NeoTreeGitConflict", { fg = colors.red })
hi("NeoTreeGitDeleted", { fg = colors.red })
hi("NeoTreeGitIgnored", { fg = colors.comment })
hi("NeoTreeGitModified", { fg = colors.yellow })
hi("NeoTreeGitUnstaged", { fg = colors.red })
hi("NeoTreeGitUntracked", { fg = colors.magenta })
hi("NeoTreeGitStaged", { fg = colors.green })
hi("NeoTreeFloatBorder", { fg = "#2a2a2a" })
hi("NeoTreeFloatTitle", { fg = colors.bright_magenta, gui = "bold" })
hi("NeoTreeTitleBar", { fg = colors.bg, bg = colors.bright_blue })
hi("NeoTreeFileNameOpened", { fg = colors.magenta })
hi("NeoTreeDimText", { fg = colors.comment })
hi("NeoTreeFilterTerm", { fg = colors.green, gui = "bold" })
hi("NeoTreeTabActive", { fg = colors.purple, bg = colors.bg, gui = "bold" })
hi("NeoTreeTabInactive", { fg = colors.comment, bg = colors.bg })
hi("NeoTreeTabSeparatorActive", { fg = colors.bg, bg = colors.bg })
hi("NeoTreeTabSeparatorInactive", { fg = colors.bg, bg = colors.bg })
hi("NeoTreeVertSplit", { fg = colors.bg, bg = colors.bg })
hi("NeoTreeWinSeparator", { fg = "#2a2a2a", bg = colors.bg })
hi("NeoTreeStatusLineNC", { fg = colors.bg, bg = colors.bg })
hi("NvimTreeNormal", { fg = colors.fg, bg = colors.bg })
hi("NvimTreeFolderName", { fg = colors.bright_blue })
hi("NvimTreeOpenedFolderName", { fg = colors.bright_blue, gui = "bold" })
hi("NvimTreeFolderIcon", { fg = colors.bright_blue })
hi("NvimTreeRootFolder", { fg = colors.bright_blue, gui = "bold" })
hi("NvimTreeGitDirty", { fg = colors.yellow })
hi("NvimTreeGitNew", { fg = colors.green })
hi("NvimTreeGitDeleted", { fg = colors.red })
hi("NvimTreeGitStaged", { fg = colors.green })
hi("NvimTreeSpecialFile", { fg = colors.magenta })
hi("NvimTreeIndentMarker", { fg = colors.comment })
hi("NvimTreeImageFile", { fg = colors.fg })
hi("NvimTreeSymlink", { fg = colors.cyan })

-- Which-key
hi("WhichKey", { fg = colors.bright_magenta })
hi("WhichKeyGroup", { fg = colors.bright_blue })
hi("WhichKeyDesc", { fg = colors.fg })
hi("WhichKeySeparator", { fg = colors.comment })

-- Notify
hi("NotifyERRORBorder", { fg = colors.red })
hi("NotifyWARNBorder", { fg = colors.yellow })
hi("NotifyINFOBorder", { fg = colors.bright_blue })
hi("NotifyDEBUGBorder", { fg = colors.comment })
hi("NotifyTRACEBorder", { fg = colors.bright_magenta })
hi("NotifyERRORIcon", { fg = colors.red })
hi("NotifyWARNIcon", { fg = colors.yellow })
hi("NotifyINFOIcon", { fg = colors.bright_blue })
hi("NotifyDEBUGIcon", { fg = colors.comment })
hi("NotifyTRACEIcon", { fg = colors.bright_magenta })
hi("NotifyERRORTitle", { fg = colors.red })
hi("NotifyWARNTitle", { fg = colors.yellow })
hi("NotifyINFOTitle", { fg = colors.bright_blue })
hi("NotifyDEBUGTitle", { fg = colors.comment })
hi("NotifyTRACETitle", { fg = colors.bright_magenta })

-- Snacks.nvim
hi("SnacksNormal", { fg = colors.fg, bg = colors.bg })
hi("SnacksNormalNC", { fg = colors.fg, bg = colors.bg })
hi("SnacksWinBar", { fg = colors.bright_magenta, gui = "bold" })
hi("SnacksWinBarNC", { fg = colors.comment })
hi("SnacksBackdrop", { fg = colors.comment })
hi("SnacksNotifierInfo", { fg = colors.bright_blue })
hi("SnacksNotifierIconInfo", { fg = colors.bright_blue })
hi("SnacksNotifierTitleInfo", { fg = colors.bright_blue, gui = "italic" })
hi("SnacksNotifierFooterInfo", { fg = colors.bright_blue })
hi("SnacksNotifierBorderInfo", { fg = colors.bright_blue })
hi("SnacksNotifierWarn", { fg = colors.yellow })
hi("SnacksNotifierIconWarn", { fg = colors.yellow })
hi("SnacksNotifierTitleWarn", { fg = colors.yellow, gui = "italic" })
hi("SnacksNotifierFooterWarn", { fg = colors.yellow })
hi("SnacksNotifierBorderWarn", { fg = colors.yellow })
hi("SnacksNotifierDebug", { fg = colors.comment })
hi("SnacksNotifierIconDebug", { fg = colors.comment })
hi("SnacksNotifierTitleDebug", { fg = colors.comment, gui = "italic" })
hi("SnacksNotifierFooterDebug", { fg = colors.bright_cyan })
hi("SnacksNotifierBorderDebug", { fg = colors.comment })
hi("SnacksNotifierError", { fg = colors.red })
hi("SnacksNotifierIconError", { fg = colors.red })
hi("SnacksNotifierTitleError", { fg = colors.red, gui = "italic" })
hi("SnacksNotifierFooterError", { fg = colors.red })
hi("SnacksNotifierBorderError", { fg = colors.red })
hi("SnacksNotifierTrace", { fg = colors.bright_magenta })
hi("SnacksNotifierIconTrace", { fg = colors.bright_magenta })
hi("SnacksNotifierTitleTrace", { fg = colors.bright_magenta, gui = "italic" })
hi("SnacksNotifierFooterTrace", { fg = colors.bright_cyan })
hi("SnacksNotifierBorderTrace", { fg = colors.bright_magenta })
hi("SnacksDashboardNormal", { fg = colors.fg, bg = colors.bg })
hi("SnacksDashboardDesc", { fg = colors.bright_blue })
hi("SnacksDashboardFile", { fg = colors.purple })
hi("SnacksDashboardDir", { fg = colors.comment })
hi("SnacksDashboardFooter", { fg = colors.yellow, gui = "italic" })
hi("SnacksDashboardHeader", { fg = colors.bright_blue })
hi("SnacksDashboardIcon", { fg = colors.magenta, gui = "bold" })
hi("SnacksDashboardKey", { fg = colors.yellow })
hi("SnacksDashboardTerminal", { fg = colors.fg, bg = colors.bg })
hi("SnacksDashboardSpecial", { fg = colors.purple })
hi("SnacksDashboardTitle", { fg = colors.bright_magenta, gui = "bold" })
hi("SnacksIndent", { fg = "#2a2a2a" })
hi("SnacksIndentScope", { fg = colors.comment })
hi("SnacksPickerSelected", { fg = colors.fg, bg = "#2a2a2a", gui = "bold" })
hi("SnacksPickerMatch", { fg = colors.bright_blue })
hi("SnacksPicker", { fg = colors.fg, bg = colors.bg })
hi("SnacksPickerBorder", { fg = "#2a2a2a" })
hi("SnacksPickerInputBorder", { fg = "#2a2a2a" })
hi("SnacksPickerInput", { fg = colors.fg, bg = colors.bg })
hi("SnacksPickerPrompt", { fg = colors.magenta })
hi("SnacksPickerTitle", { fg = colors.bg, bg = colors.purple })
hi("SnacksPickerPreviewTitle", { fg = colors.bg, bg = colors.green })
hi("SnacksPickerInputTitle", { fg = colors.bg, bg = colors.purple })
hi("SnacksPickerListTitle", { fg = colors.bg, bg = colors.bright_blue })

-- Blink.cmp
hi("BlinkCmpLabel", { fg = colors.comment })
hi("BlinkCmpLabelDeprecated", { fg = colors.comment, gui = "strikethrough" })
hi("BlinkCmpKind", { fg = colors.bright_blue })
hi("BlinkCmpMenu", { fg = colors.fg, bg = "#1a1a1a" })
hi("BlinkCmpMenuBorder", { fg = "#2a2a2a", bg = "#1a1a1a" })
hi("BlinkCmpDoc", { fg = colors.fg, bg = colors.bg })
hi("BlinkCmpDocBorder", { fg = "#2a2a2a" })
hi("BlinkCmpLabelMatch", { fg = colors.fg, gui = "bold" })
hi("BlinkCmpMenuSelection", { bg = "#2a2a2a", gui = "bold" })
hi("BlinkCmpScrollBarGutter", { bg = "#2a2a2a" })
hi("BlinkCmpScrollBarThumb", { bg = colors.comment })
hi("BlinkCmpLabelDescription", { fg = colors.comment })
hi("BlinkCmpLabelDetail", { fg = colors.comment })
hi("BlinkCmpSignatureHelpBorder", { fg = "#2a2a2a" })
hi("BlinkCmpKindText", { fg = colors.green })
hi("BlinkCmpKindMethod", { fg = colors.bright_blue })
hi("BlinkCmpKindFunction", { fg = colors.bright_blue })
hi("BlinkCmpKindConstructor", { fg = colors.bright_blue })
hi("BlinkCmpKindField", { fg = colors.green })
hi("BlinkCmpKindVariable", { fg = colors.bright_magenta })
hi("BlinkCmpKindClass", { fg = colors.yellow })
hi("BlinkCmpKindInterface", { fg = colors.yellow })
hi("BlinkCmpKindModule", { fg = colors.bright_blue })
hi("BlinkCmpKindProperty", { fg = colors.bright_blue })
hi("BlinkCmpKindUnit", { fg = colors.green })
hi("BlinkCmpKindValue", { fg = colors.yellow })
hi("BlinkCmpKindEnum", { fg = colors.yellow })
hi("BlinkCmpKindKeyword", { fg = colors.magenta })
hi("BlinkCmpKindSnippet", { fg = colors.bright_magenta })
hi("BlinkCmpKindColor", { fg = colors.red })
hi("BlinkCmpKindFile", { fg = colors.bright_blue })
hi("BlinkCmpKindReference", { fg = colors.red })
hi("BlinkCmpKindFolder", { fg = colors.bright_blue })
hi("BlinkCmpKindEnumMember", { fg = colors.cyan })
hi("BlinkCmpKindConstant", { fg = colors.yellow })
hi("BlinkCmpKindStruct", { fg = colors.bright_blue })
hi("BlinkCmpKindEvent", { fg = colors.bright_blue })
hi("BlinkCmpKindOperator", { fg = colors.bright_cyan })
hi("BlinkCmpKindTypeParameter", { fg = colors.bright_red })
hi("BlinkCmpKindCopilot", { fg = colors.cyan })

-- nvim-cmp (if using instead of blink)
hi("CmpItemAbbr", { fg = colors.comment })
hi("CmpItemAbbrDeprecated", { fg = colors.comment, gui = "strikethrough" })
hi("CmpItemKind", { fg = colors.bright_blue })
hi("CmpItemMenu", { fg = colors.fg })
hi("CmpItemAbbrMatch", { fg = colors.fg, gui = "bold" })
hi("CmpItemAbbrMatchFuzzy", { fg = colors.fg, gui = "bold" })
hi("CmpItemKindSnippet", { fg = colors.magenta })
hi("CmpItemKindKeyword", { fg = colors.red })
hi("CmpItemKindText", { fg = colors.cyan })
hi("CmpItemKindMethod", { fg = colors.bright_blue })
hi("CmpItemKindConstructor", { fg = colors.bright_blue })
hi("CmpItemKindFunction", { fg = colors.bright_blue })
hi("CmpItemKindFolder", { fg = colors.bright_blue })
hi("CmpItemKindModule", { fg = colors.bright_blue })
hi("CmpItemKindConstant", { fg = colors.yellow })
hi("CmpItemKindField", { fg = colors.green })
hi("CmpItemKindProperty", { fg = colors.green })
hi("CmpItemKindEnum", { fg = colors.green })
hi("CmpItemKindUnit", { fg = colors.green })
hi("CmpItemKindClass", { fg = colors.yellow })
hi("CmpItemKindVariable", { fg = colors.bright_magenta })
hi("CmpItemKindFile", { fg = colors.bright_blue })
hi("CmpItemKindInterface", { fg = colors.yellow })
hi("CmpItemKindColor", { fg = colors.red })
hi("CmpItemKindReference", { fg = colors.red })
hi("CmpItemKindEnumMember", { fg = colors.red })
hi("CmpItemKindStruct", { fg = colors.bright_blue })
hi("CmpItemKindValue", { fg = colors.yellow })
hi("CmpItemKindEvent", { fg = colors.bright_blue })
hi("CmpItemKindOperator", { fg = colors.bright_blue })
hi("CmpItemKindTypeParameter", { fg = colors.bright_blue })
hi("CmpItemKindCopilot", { fg = colors.cyan })

-- Flash.nvim
hi("FlashBackdrop", { fg = colors.comment })
hi("FlashLabel", { fg = colors.green, bg = colors.bg, gui = "bold" })
hi("FlashMatch", { fg = colors.purple, bg = colors.bg })
hi("FlashCurrent", { fg = colors.yellow, bg = colors.bg })
hi("FlashPrompt", { fg = colors.fg, bg = colors.bg })

-- Noice.nvim
hi("NoiceCmdline", { fg = colors.fg })
hi("NoiceCmdlineIcon", { fg = colors.bright_cyan })
hi("NoiceCmdlineIconSearch", { fg = colors.yellow })
hi("NoiceCmdlinePopup", { fg = colors.fg, bg = colors.bg })
hi("NoiceCmdlinePopupBorder", { fg = colors.purple })
hi("NoiceCmdlinePopupBorderSearch", { fg = colors.yellow })
hi("NoiceConfirmBorder", { fg = colors.bright_blue })
hi("NoiceMini", { fg = colors.comment })
hi("NoiceFormatProgressDone", { fg = colors.comment, bg = "#1a3a4a" })
hi("NoiceFormatProgressTodo", { fg = colors.comment, bg = "#1a1a1a" })
hi("NoiceVirtualText", { fg = colors.bright_cyan })
hi("NoiceLspProgressClient", { fg = colors.bright_blue })
hi("NoiceLspProgressSpinner", { fg = colors.bright_cyan })
hi("NoiceLspProgressTitle", { fg = colors.fg })

-- Indent-blankline
hi("IblIndent", { fg = "#2a2a2a" })
hi("IblScope", { fg = colors.comment })
hi("IblWhitespace", { fg = "#2a2a2a" })
hi("RainbowRed", { fg = colors.red })
hi("RainbowYellow", { fg = colors.yellow })
hi("RainbowBlue", { fg = colors.bright_blue })
hi("RainbowOrange", { fg = colors.yellow })
hi("RainbowGreen", { fg = colors.green })
hi("RainbowViolet", { fg = colors.magenta })
hi("RainbowCyan", { fg = colors.cyan })

-- Illuminate
hi("IlluminatedWordText", { bg = colors.document_highlight })
hi("IlluminatedWordRead", { bg = colors.document_highlight })
hi("IlluminatedWordWrite", { bg = colors.document_highlight })

-- Mini.nvim
hi("MiniAnimateCursor", { gui = "reverse,nocombine" })
hi("MiniAnimateNormalFloat", { fg = colors.fg, bg = colors.bg })
hi("MiniClueBorder", { fg = "#2a2a2a" })
hi("MiniClueDescGroup", { fg = colors.yellow })
hi("MiniClueDescSingle", { fg = colors.fg })
hi("MiniClueNextKey", { fg = colors.bright_cyan })
hi("MiniClueNextKeyWithPostkeys", { fg = colors.red })
hi("MiniClueSeparator", { fg = colors.bright_blue })
hi("MiniClueTitle", { fg = colors.bright_magenta, gui = "bold" })
hi("MiniCompletionActiveParameter", { gui = "underline" })
hi("MiniCursorword", { gui = "underline" })
hi("MiniCursorwordCurrent", { gui = "underline" })
hi("MiniDepsChangeAdded", { fg = colors.green })
hi("MiniDepsChangeRemoved", { fg = colors.red })
hi("MiniDepsHint", { fg = colors.bright_cyan })
hi("MiniDepsInfo", { fg = colors.bright_blue })
hi("MiniDepsMsgBreaking", { fg = colors.yellow })
hi("MiniDepsPlaceholder", { fg = colors.comment })
hi("MiniDepsTitle", { fg = colors.bright_magenta, gui = "bold" })
hi("MiniDepsTitleError", { fg = colors.bg, bg = colors.red })
hi("MiniDepsTitleSame", { fg = colors.bright_blue, bg = "#0a1a2a" })
hi("MiniDepsTitleUpdate", { fg = colors.bg, bg = colors.green })
hi("MiniDiffSignAdd", { fg = colors.green })
hi("MiniDiffSignChange", { fg = colors.yellow })
hi("MiniDiffSignDelete", { fg = colors.red })
hi("MiniDiffOverAdd", { fg = colors.bright_green, bg = "#0a2a14" })
hi("MiniDiffOverChange", { fg = colors.bright_blue, bg = "#0a1a2a" })
hi("MiniDiffOverContext", { fg = colors.bright_yellow, bg = "#2a2a0a" })
hi("MiniDiffOverDelete", { fg = colors.red, bg = "#2a0a0a" })
hi("MiniFilesBorder", { fg = "#2a2a2a" })
hi("MiniFilesBorderModified", { fg = colors.yellow })
hi("MiniFilesCursorLine", { bg = colors.line_highlight })
hi("MiniFilesDirectory", { fg = colors.bright_blue })
hi("MiniFilesFile", { fg = colors.fg })
hi("MiniFilesNormal", { fg = colors.fg, bg = colors.bg })
hi("MiniFilesTitle", { fg = colors.bright_magenta, gui = "bold" })
hi("MiniFilesTitleFocused", { fg = colors.bg, bg = colors.magenta, gui = "bold" })
hi("MiniHipatternsFixme", { fg = colors.bg, bg = colors.red, gui = "bold" })
hi("MiniHipatternsHack", { fg = colors.bg, bg = colors.yellow, gui = "bold" })
hi("MiniHipatternsNote", { fg = colors.bg, bg = colors.bright_cyan, gui = "bold" })
hi("MiniHipatternsTodo", { fg = colors.bg, bg = colors.cyan, gui = "bold" })
hi("MiniIconsAzure", { fg = colors.bright_cyan })
hi("MiniIconsBlue", { fg = colors.bright_blue })
hi("MiniIconsCyan", { fg = colors.cyan })
hi("MiniIconsGreen", { fg = colors.green })
hi("MiniIconsGrey", { fg = colors.fg })
hi("MiniIconsOrange", { fg = colors.yellow })
hi("MiniIconsPurple", { fg = colors.magenta })
hi("MiniIconsRed", { fg = colors.red })
hi("MiniIconsYellow", { fg = colors.yellow })
hi("MiniIndentscopeSymbol", { fg = colors.comment })
hi("MiniJump", { fg = colors.comment, bg = colors.magenta })
hi("MiniJump2dDim", { fg = colors.comment })
hi("MiniJump2dSpot", { fg = colors.yellow, bg = colors.bg, gui = "bold,underline" })
hi("MiniJump2dSpotAhead", { fg = colors.cyan, bg = colors.line_highlight })
hi("MiniJump2dSpotUnique", { fg = colors.bright_cyan, bg = colors.bg, gui = "bold" })
hi("MiniMapNormal", { fg = colors.fg, bg = colors.bg })
hi("MiniMapSymbolCount", { fg = colors.purple })
hi("MiniMapSymbolLine", { fg = colors.bright_magenta })
hi("MiniMapSymbolView", { fg = colors.fg })
hi("MiniNotifyBorder", { fg = "#2a2a2a" })
hi("MiniNotifyNormal", { fg = colors.fg, bg = colors.bg })
hi("MiniNotifyTitle", { fg = colors.bright_magenta, gui = "bold" })
hi("MiniOperatorsExchangeFrom", { fg = colors.bg, bg = colors.bright_yellow })
hi("MiniPickBorder", { fg = "#2a2a2a" })
hi("MiniPickBorderBusy", { fg = colors.yellow })
hi("MiniPickBorderText", { fg = colors.magenta })
hi("MiniPickIconDirectory", { fg = colors.bright_blue })
hi("MiniPickIconFile", { fg = colors.fg })
hi("MiniPickHeader", { fg = colors.bright_cyan })
hi("MiniPickMatchCurrent", { fg = colors.bright_magenta, bg = "#2a2a2a", gui = "bold" })
hi("MiniPickMatchMarked", { bg = colors.visual })
hi("MiniPickMatchRanges", { fg = colors.bright_cyan })
hi("MiniPickNormal", { fg = colors.fg, bg = colors.bg })
hi("MiniPickPreviewLine", { bg = colors.line_highlight })
hi("MiniPickPreviewRegion", { fg = colors.bg, bg = colors.bright_yellow })
hi("MiniPickPrompt", { fg = colors.fg, bg = colors.bg })
hi("MiniPickPromptCaret", { fg = colors.magenta })
hi("MiniPickPromptPrefix", { fg = colors.magenta })
hi("MiniStarterCurrent", { fg = colors.fg })
hi("MiniStarterFooter", { fg = colors.yellow, gui = "italic" })
hi("MiniStarterHeader", { fg = colors.bright_blue })
hi("MiniStarterInactive", { fg = colors.comment, gui = "italic" })
hi("MiniStarterItem", { fg = colors.fg })
hi("MiniStarterItemBullet", { fg = colors.bright_blue })
hi("MiniStarterItemPrefix", { fg = colors.magenta })
hi("MiniStarterSection", { fg = colors.bright_magenta })
hi("MiniStarterQuery", { fg = colors.green })
hi("MiniStatuslineDevinfo", { fg = colors.fg, bg = "#2a2a2a" })
hi("MiniStatuslineFileinfo", { fg = colors.fg, bg = "#2a2a2a" })
hi("MiniStatuslineFilename", { fg = colors.fg, bg = "#1a1a1a" })
hi("MiniStatuslineInactive", { fg = colors.bright_blue, bg = "#1a1a1a" })
hi("MiniStatuslineModeCommand", { fg = colors.bg, bg = colors.yellow, gui = "bold" })
hi("MiniStatuslineModeInsert", { fg = colors.bg, bg = colors.green, gui = "bold" })
hi("MiniStatuslineModeNormal", { fg = colors.bg, bg = colors.bright_blue, gui = "bold" })
hi("MiniStatuslineModeOther", { fg = colors.bg, bg = colors.cyan, gui = "bold" })
hi("MiniStatuslineModeReplace", { fg = colors.bg, bg = colors.red, gui = "bold" })
hi("MiniStatuslineModeVisual", { fg = colors.bg, bg = colors.magenta, gui = "bold" })
hi("MiniSurround", { fg = "#2a2a2a", bg = colors.magenta })
hi("MiniTablineCurrent", { fg = colors.fg, bg = colors.bg, sp = colors.red, gui = "bold,italic,underline" })
hi("MiniTablineFill", { bg = colors.bg })
hi("MiniTablineHidden", { fg = colors.fg, bg = "#1a1a1a" })
hi("MiniTablineModifiedCurrent", { fg = colors.red, gui = "bold,italic" })
hi("MiniTablineModifiedHidden", { fg = colors.red })
hi("MiniTablineModifiedVisible", { fg = colors.red })
hi("MiniTablineTabpagesection", { fg = "#2a2a2a", bg = colors.bg })
hi("MiniTablineVisible", { bg = colors.bg })
hi("MiniTestEmphasis", { gui = "bold" })
hi("MiniTestFail", { fg = colors.red, gui = "bold" })
hi("MiniTestPass", { fg = colors.green, gui = "bold" })
hi("MiniTrailspace", { bg = colors.red })
